### ISSUE TITLE
Taskbar

### ISSUE THREAD

**Issue by Prinzip** [CNParent/poe-ladder#2]
Hello.

If the Tool is running, the Taskbar is all time shown above the Game in Fullscreen Window Mode. Can u please fix that? Also a checkbox for saving the charname & legue is a nice to have :)

**Comment by CNParent** [comment]
Defaults are in the newest release, as is a potential fix to the taskbar issue when running PoE in fullscreen windowed mode. Please let me know if v1.0.3 fixes your issues, as I wasn't able to reproduce the issue.

Thanks!

**Comment by Prinzip** [comment]
The defaults are nice :+1: 
The Taskbar is also in v.1.0.3 on top in window mode, so not fixed. Here is a Screen: http://www2.pic-upload.de/img/31633988/taskbar.jpg

**Comment by CNParent** [comment]
Very strange. I'm running Windows 10 myself and can't seem to reproduce this behavior regardless of taskbar settings. It's expected that if you click anywhere on the tracker window while in game the taskbar will show, but as long as Path of Exile is the focused window the task bar should remain hidden. 

If you could send me a screenshot of your taskbar properties, I'll try again to reproduce the issue, but in the meantime I would recommend setting your taskbar to auto-hide. I know it's not ideal, but it may achieve the same result.

Thanks for the update

**Comment by Prinzip** [comment]
I'm using Windows 10 Professional and here are my taskbar settings: http://www2.pic-upload.de/img/31637870/task2.jpg

**Comment by dsnvwlmnt** [comment]
I have the same problem, still in v103. Windows 10 Home.

**Comment by CNParent** [comment]
A couple more questions to help me out here:

1. Is the taskbar on top when PoE is in borderless window mode normally?
2. Is the taskbar on top while the tacker is activated, deactivated, or both?
3. Are you using any third party display tools?

I've released v1.0.4 which upgrades the application from using Electron v1.3.4 to v1.4.2 - I've found reports of this issue elsewhere earlier this year, so it's possible this will have solved the issue regardless.

**Comment by dsnvwlmnt** [comment]
In v1.0.3 and still v1.0.4:

> **Is the taskbar on top when PoE is in borderless window mode normally?**
No, only when running PoELadder does the taskbar obstruct PoE.

> **Is the taskbar on top while the tracker is activated, deactivated, or both?**
Only when activated.

> **Are you using any third party display tools?**
No, but i launch PoE with an autohotkey macro, which sits in the taskbar. It causes no taskbar issues like PoELadder. Here's the code if ever you need to look at it: http://pastebin.com/W7pYHeEZ

**Comment by CNParent** [comment]
Latest windows update allowed me to reproduce the error, I've released version 1.0.5 that solves this issue.

**Comment by Prinzip** [comment]
now its fixed, thank u
