### ISSUE TITLE
PoELadder Does Not Work with Streaming (OBS Studio)

### ISSUE THREAD

**Issue by dsnvwlmnt** [CNParent/poe-ladder#4]
There seems to be something abnormal you are doing which makes it so that we can't stream this. Would love to be able to.

If i use the ubiquitous OBS Window Capture, if PoELadder is started (STARTED/stop), it doesn't appear in the list of windows available to add. Perhaps related to what you do that makes it not appear in the alt+tab list. But perhaps not.

If PoELadder isn't started (start/STOPPED), i'm able to capture the window, but the PoELadder window appears solid black. So it seems clear something non-standard is being used here as well, even with just the PoELadder program simply opened.

If i click START in the latter scenario, the window promptly disappears from the stream.

**Comment by CNParent** [comment]
There are a couple of factors contributing to this issue.

I'm not able to make the window visible to OBS when the tracker is started without causing the taskbar to be always on top. ([See this microsoft community thread](http://answers.microsoft.com/en-us/windows/forum/windows_10-start/windows-10-brings-taskbar-on-top-of-fullscreen/efa61fb2-81e5-4a08-b40c-5e91d297f465)) To address this, I'm launching the window in toolbar mode, which has the unfortunate side-effect of making the window invisible to obs (and likely many other programs as well).

Second, OBS cannot display chrome windows that have hardware acceleration enabled. I cannot disable hardware acceleration and also have a transparent window as far as I'm aware, which causes the solid black appearance of the window in OBS.

In the meantime, you could always use the display capture source, and crop the window (alt+drag the scene edges) as a work around. If Microsoft manages to fix the issue I referred to above, I'll explore some more options related to the second.

Sorry I can't give a better answer to this right now!
