### ISSUE TITLE
GGG re-added Ladders, but POELadder Won't Show Rank

### ISSUE THREAD

**Issue by dsnvwlmnt** [CNParent/poe-ladder#5]
GGG recently re-added direct access to 15,000 players per ladder. However, when you Start the POELadder search, it fetches forever. Perhaps they changed the api a little bit and this would require a small update?

**Comment by dsnvwlmnt** [comment]
Hmm maybe i was wrong. It took about 5 minutes, but it eventually worked...

**Comment by CNParent** [comment]
Thanks for opening this issue!

GGG decreased the rate that the ladder API can be hit, which was causing the app to enter a 30 second cool-down. I've released a new version that retrieves the ladder rankings more slowly, which ends up finding a character's rank more quickly overall.

**Comment by dhuber666** [comment]
Do you know how many requests you can do per second? 
I googled that for a while but can't find anything related to it. 

What I found was that you can just fetch 200 results per request.
